// Code generated by protoc-gen-go. DO NOT EDIT.
// source: slave.proto

package gobuildslave

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequirementCategory int32

const (
	RequirementCategory_UNKNOWN      RequirementCategory = 0
	RequirementCategory_DISK         RequirementCategory = 1
	RequirementCategory_EXTERNAL     RequirementCategory = 2
	RequirementCategory_SERVER       RequirementCategory = 3
	RequirementCategory_NETWORK      RequirementCategory = 4
	RequirementCategory_ACCESS_POINT RequirementCategory = 5
)

var RequirementCategory_name = map[int32]string{
	0: "UNKNOWN",
	1: "DISK",
	2: "EXTERNAL",
	3: "SERVER",
	4: "NETWORK",
	5: "ACCESS_POINT",
}

var RequirementCategory_value = map[string]int32{
	"UNKNOWN":      0,
	"DISK":         1,
	"EXTERNAL":     2,
	"SERVER":       3,
	"NETWORK":      4,
	"ACCESS_POINT": 5,
}

func (x RequirementCategory) String() string {
	return proto.EnumName(RequirementCategory_name, int32(x))
}

func (RequirementCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{0}
}

type State int32

const (
	State_ACKNOWLEDGED    State = 0
	State_BUILDING        State = 1
	State_BUILT           State = 2
	State_RUNNING         State = 3
	State_UPDATE_STARTING State = 4
	State_UPDATING        State = 5
	State_KILLING         State = 6
	State_DEAD            State = 7
	State_PENDING         State = 8
	State_DIED            State = 9
	State_BRINK_OF_DEATH  State = 10
)

var State_name = map[int32]string{
	0:  "ACKNOWLEDGED",
	1:  "BUILDING",
	2:  "BUILT",
	3:  "RUNNING",
	4:  "UPDATE_STARTING",
	5:  "UPDATING",
	6:  "KILLING",
	7:  "DEAD",
	8:  "PENDING",
	9:  "DIED",
	10: "BRINK_OF_DEATH",
}

var State_value = map[string]int32{
	"ACKNOWLEDGED":    0,
	"BUILDING":        1,
	"BUILT":           2,
	"RUNNING":         3,
	"UPDATE_STARTING": 4,
	"UPDATING":        5,
	"KILLING":         6,
	"DEAD":            7,
	"PENDING":         8,
	"DIED":            9,
	"BRINK_OF_DEATH":  10,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{1}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Requirement struct {
	Category             RequirementCategory `protobuf:"varint,1,opt,name=category,proto3,enum=gobuildslave.RequirementCategory" json:"category,omitempty"`
	Properties           string              `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Requirement) Reset()         { *m = Requirement{} }
func (m *Requirement) String() string { return proto.CompactTextString(m) }
func (*Requirement) ProtoMessage()    {}
func (*Requirement) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{1}
}

func (m *Requirement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirement.Unmarshal(m, b)
}
func (m *Requirement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirement.Marshal(b, m, deterministic)
}
func (m *Requirement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirement.Merge(m, src)
}
func (m *Requirement) XXX_Size() int {
	return xxx_messageInfo_Requirement.Size(m)
}
func (m *Requirement) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirement.DiscardUnknown(m)
}

var xxx_messageInfo_Requirement proto.InternalMessageInfo

func (m *Requirement) GetCategory() RequirementCategory {
	if m != nil {
		return m.Category
	}
	return RequirementCategory_UNKNOWN
}

func (m *Requirement) GetProperties() string {
	if m != nil {
		return m.Properties
	}
	return ""
}

type Job struct {
	Name         string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GoPath       string         `protobuf:"bytes,2,opt,name=go_path,json=goPath,proto3" json:"go_path,omitempty"`
	Requirements []*Requirement `protobuf:"bytes,3,rep,name=requirements,proto3" json:"requirements,omitempty"`
	Sudo         bool           `protobuf:"varint,4,opt,name=sudo,proto3" json:"sudo,omitempty"`
	Bootstrap    bool           `protobuf:"varint,5,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	Breakout     bool           `protobuf:"varint,6,opt,name=breakout,proto3" json:"breakout,omitempty"`
	// We partial bootstrap if we need something to come up
	// when it doesn't currently exist.
	PartialBootstrap     bool     `protobuf:"varint,7,opt,name=partial_bootstrap,json=partialBootstrap,proto3" json:"partial_bootstrap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{2}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Job) GetGoPath() string {
	if m != nil {
		return m.GoPath
	}
	return ""
}

func (m *Job) GetRequirements() []*Requirement {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *Job) GetSudo() bool {
	if m != nil {
		return m.Sudo
	}
	return false
}

func (m *Job) GetBootstrap() bool {
	if m != nil {
		return m.Bootstrap
	}
	return false
}

func (m *Job) GetBreakout() bool {
	if m != nil {
		return m.Breakout
	}
	return false
}

func (m *Job) GetPartialBootstrap() bool {
	if m != nil {
		return m.PartialBootstrap
	}
	return false
}

type JobAssignment struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Host                 string   `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	State                State    `protobuf:"varint,4,opt,name=state,proto3,enum=gobuildslave.State" json:"state,omitempty"`
	StartTime            int64    `protobuf:"varint,6,opt,name=startTime,proto3" json:"startTime,omitempty"`
	CommandKey           string   `protobuf:"bytes,7,opt,name=command_key,json=commandKey,proto3" json:"command_key,omitempty"`
	BuildFail            int32    `protobuf:"varint,8,opt,name=build_fail,json=buildFail,proto3" json:"build_fail,omitempty"`
	RunningVersion       string   `protobuf:"bytes,9,opt,name=running_version,json=runningVersion,proto3" json:"running_version,omitempty"`
	DiscoverCount        int32    `protobuf:"varint,10,opt,name=discover_count,json=discoverCount,proto3" json:"discover_count,omitempty"`
	Status               string   `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	LastTransitionTime   int64    `protobuf:"varint,12,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	QueuePos             int32    `protobuf:"varint,13,opt,name=queue_pos,json=queuePos,proto3" json:"queue_pos,omitempty"`
	LastVersionPull      int64    `protobuf:"varint,14,opt,name=last_version_pull,json=lastVersionPull,proto3" json:"last_version_pull,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobAssignment) Reset()         { *m = JobAssignment{} }
func (m *JobAssignment) String() string { return proto.CompactTextString(m) }
func (*JobAssignment) ProtoMessage()    {}
func (*JobAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{3}
}

func (m *JobAssignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobAssignment.Unmarshal(m, b)
}
func (m *JobAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobAssignment.Marshal(b, m, deterministic)
}
func (m *JobAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobAssignment.Merge(m, src)
}
func (m *JobAssignment) XXX_Size() int {
	return xxx_messageInfo_JobAssignment.Size(m)
}
func (m *JobAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_JobAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_JobAssignment proto.InternalMessageInfo

func (m *JobAssignment) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *JobAssignment) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *JobAssignment) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *JobAssignment) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *JobAssignment) GetState() State {
	if m != nil {
		return m.State
	}
	return State_ACKNOWLEDGED
}

func (m *JobAssignment) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *JobAssignment) GetCommandKey() string {
	if m != nil {
		return m.CommandKey
	}
	return ""
}

func (m *JobAssignment) GetBuildFail() int32 {
	if m != nil {
		return m.BuildFail
	}
	return 0
}

func (m *JobAssignment) GetRunningVersion() string {
	if m != nil {
		return m.RunningVersion
	}
	return ""
}

func (m *JobAssignment) GetDiscoverCount() int32 {
	if m != nil {
		return m.DiscoverCount
	}
	return 0
}

func (m *JobAssignment) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *JobAssignment) GetLastTransitionTime() int64 {
	if m != nil {
		return m.LastTransitionTime
	}
	return 0
}

func (m *JobAssignment) GetQueuePos() int32 {
	if m != nil {
		return m.QueuePos
	}
	return 0
}

func (m *JobAssignment) GetLastVersionPull() int64 {
	if m != nil {
		return m.LastVersionPull
	}
	return 0
}

type SlaveConfig struct {
	Requirements         []*Requirement `protobuf:"bytes,1,rep,name=requirements,proto3" json:"requirements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SlaveConfig) Reset()         { *m = SlaveConfig{} }
func (m *SlaveConfig) String() string { return proto.CompactTextString(m) }
func (*SlaveConfig) ProtoMessage()    {}
func (*SlaveConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{4}
}

func (m *SlaveConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlaveConfig.Unmarshal(m, b)
}
func (m *SlaveConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlaveConfig.Marshal(b, m, deterministic)
}
func (m *SlaveConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlaveConfig.Merge(m, src)
}
func (m *SlaveConfig) XXX_Size() int {
	return xxx_messageInfo_SlaveConfig.Size(m)
}
func (m *SlaveConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SlaveConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SlaveConfig proto.InternalMessageInfo

func (m *SlaveConfig) GetRequirements() []*Requirement {
	if m != nil {
		return m.Requirements
	}
	return nil
}

type JobSpec struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	Disk                 int64    `protobuf:"varint,3,opt,name=disk,proto3" json:"disk,omitempty"`
	Args                 []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	External             bool     `protobuf:"varint,5,opt,name=external,proto3" json:"external,omitempty"`
	Host                 string   `protobuf:"bytes,6,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	Cds                  bool     `protobuf:"varint,8,opt,name=cds,proto3" json:"cds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobSpec) Reset()         { *m = JobSpec{} }
func (m *JobSpec) String() string { return proto.CompactTextString(m) }
func (*JobSpec) ProtoMessage()    {}
func (*JobSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{5}
}

func (m *JobSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobSpec.Unmarshal(m, b)
}
func (m *JobSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobSpec.Marshal(b, m, deterministic)
}
func (m *JobSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobSpec.Merge(m, src)
}
func (m *JobSpec) XXX_Size() int {
	return xxx_messageInfo_JobSpec.Size(m)
}
func (m *JobSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_JobSpec.DiscardUnknown(m)
}

var xxx_messageInfo_JobSpec proto.InternalMessageInfo

func (m *JobSpec) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobSpec) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func (m *JobSpec) GetDisk() int64 {
	if m != nil {
		return m.Disk
	}
	return 0
}

func (m *JobSpec) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *JobSpec) GetExternal() bool {
	if m != nil {
		return m.External
	}
	return false
}

func (m *JobSpec) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *JobSpec) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *JobSpec) GetCds() bool {
	if m != nil {
		return m.Cds
	}
	return false
}

type JobDetails struct {
	Spec                 *JobSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=state,proto3,enum=gobuildslave.State" json:"state,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TestCount            int32    `protobuf:"varint,4,opt,name=test_count,json=testCount,proto3" json:"test_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobDetails) Reset()         { *m = JobDetails{} }
func (m *JobDetails) String() string { return proto.CompactTextString(m) }
func (*JobDetails) ProtoMessage()    {}
func (*JobDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{6}
}

func (m *JobDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDetails.Unmarshal(m, b)
}
func (m *JobDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDetails.Marshal(b, m, deterministic)
}
func (m *JobDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDetails.Merge(m, src)
}
func (m *JobDetails) XXX_Size() int {
	return xxx_messageInfo_JobDetails.Size(m)
}
func (m *JobDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDetails.DiscardUnknown(m)
}

var xxx_messageInfo_JobDetails proto.InternalMessageInfo

func (m *JobDetails) GetSpec() *JobSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *JobDetails) GetState() State {
	if m != nil {
		return m.State
	}
	return State_ACKNOWLEDGED
}

func (m *JobDetails) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *JobDetails) GetTestCount() int32 {
	if m != nil {
		return m.TestCount
	}
	return 0
}

type JobList struct {
	Details              []*JobDetails `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JobList) Reset()         { *m = JobList{} }
func (m *JobList) String() string { return proto.CompactTextString(m) }
func (*JobList) ProtoMessage()    {}
func (*JobList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{7}
}

func (m *JobList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobList.Unmarshal(m, b)
}
func (m *JobList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobList.Marshal(b, m, deterministic)
}
func (m *JobList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobList.Merge(m, src)
}
func (m *JobList) XXX_Size() int {
	return xxx_messageInfo_JobList.Size(m)
}
func (m *JobList) XXX_DiscardUnknown() {
	xxx_messageInfo_JobList.DiscardUnknown(m)
}

var xxx_messageInfo_JobList proto.InternalMessageInfo

func (m *JobList) GetDetails() []*JobDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

type Config struct {
	Memory               int64    `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk                 int64    `protobuf:"varint,2,opt,name=disk,proto3" json:"disk,omitempty"`
	External             bool     `protobuf:"varint,3,opt,name=external,proto3" json:"external,omitempty"`
	GoVersion            string   `protobuf:"bytes,4,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	SupportsCds          bool     `protobuf:"varint,5,opt,name=supports_cds,json=supportsCds,proto3" json:"supports_cds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{8}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetMemory() int64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Config) GetDisk() int64 {
	if m != nil {
		return m.Disk
	}
	return 0
}

func (m *Config) GetExternal() bool {
	if m != nil {
		return m.External
	}
	return false
}

func (m *Config) GetGoVersion() string {
	if m != nil {
		return m.GoVersion
	}
	return ""
}

func (m *Config) GetSupportsCds() bool {
	if m != nil {
		return m.SupportsCds
	}
	return false
}

type RunRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunRequest) Reset()         { *m = RunRequest{} }
func (m *RunRequest) String() string { return proto.CompactTextString(m) }
func (*RunRequest) ProtoMessage()    {}
func (*RunRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{9}
}

func (m *RunRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunRequest.Unmarshal(m, b)
}
func (m *RunRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunRequest.Marshal(b, m, deterministic)
}
func (m *RunRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunRequest.Merge(m, src)
}
func (m *RunRequest) XXX_Size() int {
	return xxx_messageInfo_RunRequest.Size(m)
}
func (m *RunRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunRequest proto.InternalMessageInfo

func (m *RunRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type RunResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunResponse) Reset()         { *m = RunResponse{} }
func (m *RunResponse) String() string { return proto.CompactTextString(m) }
func (*RunResponse) ProtoMessage()    {}
func (*RunResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{10}
}

func (m *RunResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunResponse.Unmarshal(m, b)
}
func (m *RunResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunResponse.Marshal(b, m, deterministic)
}
func (m *RunResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunResponse.Merge(m, src)
}
func (m *RunResponse) XXX_Size() int {
	return xxx_messageInfo_RunResponse.Size(m)
}
func (m *RunResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunResponse proto.InternalMessageInfo

type UpdateRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{11}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type UpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{12}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

type KillRequest struct {
	Job                  *Job     `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillRequest) Reset()         { *m = KillRequest{} }
func (m *KillRequest) String() string { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()    {}
func (*KillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{13}
}

func (m *KillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillRequest.Unmarshal(m, b)
}
func (m *KillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillRequest.Marshal(b, m, deterministic)
}
func (m *KillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillRequest.Merge(m, src)
}
func (m *KillRequest) XXX_Size() int {
	return xxx_messageInfo_KillRequest.Size(m)
}
func (m *KillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillRequest proto.InternalMessageInfo

func (m *KillRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type KillResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillResponse) Reset()         { *m = KillResponse{} }
func (m *KillResponse) String() string { return proto.CompactTextString(m) }
func (*KillResponse) ProtoMessage()    {}
func (*KillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{14}
}

func (m *KillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillResponse.Unmarshal(m, b)
}
func (m *KillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillResponse.Marshal(b, m, deterministic)
}
func (m *KillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillResponse.Merge(m, src)
}
func (m *KillResponse) XXX_Size() int {
	return xxx_messageInfo_KillResponse.Size(m)
}
func (m *KillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{15}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Jobs                 []*JobAssignment `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{16}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetJobs() []*JobAssignment {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type ConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{17}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

type ConfigResponse struct {
	Config               *SlaveConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5203a3ed916706d4, []int{18}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetConfig() *SlaveConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

func init() {
	proto.RegisterEnum("gobuildslave.RequirementCategory", RequirementCategory_name, RequirementCategory_value)
	proto.RegisterEnum("gobuildslave.State", State_name, State_value)
	proto.RegisterType((*Empty)(nil), "gobuildslave.Empty")
	proto.RegisterType((*Requirement)(nil), "gobuildslave.Requirement")
	proto.RegisterType((*Job)(nil), "gobuildslave.Job")
	proto.RegisterType((*JobAssignment)(nil), "gobuildslave.JobAssignment")
	proto.RegisterType((*SlaveConfig)(nil), "gobuildslave.SlaveConfig")
	proto.RegisterType((*JobSpec)(nil), "gobuildslave.JobSpec")
	proto.RegisterType((*JobDetails)(nil), "gobuildslave.JobDetails")
	proto.RegisterType((*JobList)(nil), "gobuildslave.JobList")
	proto.RegisterType((*Config)(nil), "gobuildslave.Config")
	proto.RegisterType((*RunRequest)(nil), "gobuildslave.RunRequest")
	proto.RegisterType((*RunResponse)(nil), "gobuildslave.RunResponse")
	proto.RegisterType((*UpdateRequest)(nil), "gobuildslave.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "gobuildslave.UpdateResponse")
	proto.RegisterType((*KillRequest)(nil), "gobuildslave.KillRequest")
	proto.RegisterType((*KillResponse)(nil), "gobuildslave.KillResponse")
	proto.RegisterType((*ListRequest)(nil), "gobuildslave.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "gobuildslave.ListResponse")
	proto.RegisterType((*ConfigRequest)(nil), "gobuildslave.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "gobuildslave.ConfigResponse")
}

func init() { proto.RegisterFile("slave.proto", fileDescriptor_5203a3ed916706d4) }

var fileDescriptor_5203a3ed916706d4 = []byte{
	// 1212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x5d, 0x92, 0xda, 0x46,
	0x17, 0x45, 0x08, 0x04, 0xba, 0x02, 0x46, 0x6e, 0xfb, 0xf3, 0x27, 0x63, 0x4f, 0x32, 0x56, 0x2a,
	0x95, 0xb1, 0x53, 0xe5, 0xc4, 0xd8, 0x95, 0xca, 0x8b, 0xcb, 0xc5, 0x80, 0x3c, 0x1e, 0xa0, 0x98,
	0xa9, 0x86, 0xb1, 0xf3, 0xa6, 0x92, 0xa0, 0x8d, 0x65, 0x0b, 0xb5, 0xac, 0x6e, 0x4d, 0x65, 0xb6,
	0x91, 0x15, 0xe4, 0x21, 0x3b, 0xc8, 0x72, 0xf2, 0x92, 0x05, 0x78, 0x11, 0xa9, 0x6e, 0x89, 0xdf,
	0x21, 0x3f, 0xbc, 0x75, 0x9f, 0x7b, 0xef, 0x51, 0xdf, 0x73, 0x4f, 0x37, 0x80, 0xc1, 0x42, 0xef,
	0x8a, 0x3c, 0x89, 0x13, 0xca, 0x29, 0xaa, 0xcd, 0xa8, 0x9f, 0x06, 0xe1, 0x54, 0x62, 0x76, 0x05,
	0xca, 0xce, 0x3c, 0xe6, 0xd7, 0x76, 0x08, 0x06, 0x26, 0x9f, 0xd2, 0x20, 0x21, 0x73, 0x12, 0x71,
	0xf4, 0x02, 0xaa, 0x13, 0x8f, 0x93, 0x19, 0x4d, 0xae, 0x2d, 0xe5, 0x48, 0x39, 0x6e, 0xb4, 0x1e,
	0x3e, 0x59, 0x2f, 0x7c, 0xb2, 0x96, 0xdc, 0xc9, 0x13, 0xf1, 0xb2, 0x04, 0x7d, 0x01, 0x10, 0x27,
	0x34, 0x26, 0x09, 0x0f, 0x08, 0xb3, 0x8a, 0x47, 0xca, 0xb1, 0x8e, 0xd7, 0x10, 0xfb, 0xb3, 0x02,
	0x6a, 0x8f, 0xfa, 0x08, 0x41, 0x29, 0xf2, 0xe6, 0x44, 0x7e, 0x42, 0xc7, 0x72, 0x8d, 0xfe, 0x0f,
	0x95, 0x19, 0x75, 0x63, 0x8f, 0xbf, 0xcf, 0x0b, 0xb5, 0x19, 0xbd, 0xf0, 0xf8, 0x7b, 0xf4, 0x02,
	0x6a, 0xc9, 0xea, 0xab, 0xcc, 0x52, 0x8f, 0xd4, 0x63, 0xa3, 0x75, 0xef, 0x6f, 0xcf, 0x85, 0x37,
	0xd2, 0xc5, 0xb7, 0x58, 0x3a, 0xa5, 0x56, 0xe9, 0x48, 0x39, 0xae, 0x62, 0xb9, 0x46, 0x0f, 0x40,
	0xf7, 0x29, 0xe5, 0x8c, 0x27, 0x5e, 0x6c, 0x95, 0x65, 0x60, 0x05, 0xa0, 0x26, 0x54, 0xfd, 0x84,
	0x78, 0x1f, 0x69, 0xca, 0x2d, 0x4d, 0x06, 0x97, 0x7b, 0xf4, 0x2d, 0xdc, 0x8a, 0xbd, 0x84, 0x07,
	0x5e, 0xe8, 0xae, 0x18, 0x2a, 0x32, 0xc9, 0xcc, 0x03, 0x27, 0x0b, 0xdc, 0xfe, 0x53, 0x85, 0x7a,
	0x8f, 0xfa, 0x6d, 0xc6, 0x82, 0x59, 0x24, 0xf5, 0xfd, 0x0a, 0xd4, 0x0f, 0xd4, 0x97, 0x7d, 0x1b,
	0xad, 0x5b, 0x9b, 0x2d, 0xf4, 0xa8, 0x8f, 0x45, 0x14, 0xdd, 0x05, 0x8d, 0x91, 0xe4, 0x8a, 0x24,
	0x0b, 0x21, 0xb2, 0x9d, 0xe8, 0xe4, 0x3d, 0x65, 0x5c, 0x1e, 0x58, 0xc7, 0x72, 0x2d, 0xb0, 0x98,
	0x26, 0xdc, 0x52, 0x8f, 0x94, 0xe3, 0x32, 0x96, 0x6b, 0xf4, 0x08, 0xca, 0x8c, 0x7b, 0x9c, 0xc8,
	0x96, 0x1b, 0xad, 0xdb, 0x9b, 0x9f, 0x19, 0x89, 0x10, 0xce, 0x32, 0x84, 0x10, 0x8c, 0x7b, 0x09,
	0x1f, 0x07, 0x73, 0x22, 0x7b, 0x55, 0xf1, 0x0a, 0x40, 0x5f, 0x82, 0x31, 0xa1, 0xf3, 0xb9, 0x17,
	0x4d, 0xdd, 0x8f, 0xe4, 0x5a, 0xb6, 0xa9, 0x63, 0xc8, 0xa1, 0x3e, 0xb9, 0x46, 0x87, 0x00, 0x92,
	0xd9, 0x7d, 0xe7, 0x05, 0xa1, 0x55, 0x95, 0x67, 0xd0, 0x25, 0xf2, 0xca, 0x0b, 0x42, 0xf4, 0x0d,
	0x1c, 0x24, 0x69, 0x14, 0x05, 0xd1, 0xcc, 0xbd, 0x22, 0x09, 0x0b, 0x68, 0x64, 0xe9, 0x92, 0xa3,
	0x91, 0xc3, 0x6f, 0x32, 0x14, 0x7d, 0x0d, 0x8d, 0x69, 0xc0, 0x26, 0xf4, 0x8a, 0x24, 0xee, 0x84,
	0xa6, 0x11, 0xb7, 0x40, 0x72, 0xd5, 0x17, 0x68, 0x47, 0x80, 0x52, 0x18, 0xee, 0xf1, 0x94, 0x59,
	0x46, 0x2e, 0x8c, 0xdc, 0xa1, 0xef, 0xe1, 0x4e, 0xe8, 0x31, 0xee, 0xf2, 0xc4, 0x8b, 0x58, 0xc0,
	0x03, 0x1a, 0xb9, 0x5c, 0x34, 0x54, 0x93, 0x0d, 0x21, 0x11, 0x1b, 0x2f, 0x43, 0xb2, 0xb3, 0xfb,
	0xa0, 0x7f, 0x4a, 0x49, 0x4a, 0xdc, 0x98, 0x32, 0xab, 0x2e, 0xbf, 0x55, 0x95, 0xc0, 0x05, 0x65,
	0xe8, 0x31, 0xdc, 0x92, 0x74, 0xf9, 0x99, 0xdd, 0x38, 0x0d, 0x43, 0xab, 0x21, 0xb9, 0x0e, 0x44,
	0x20, 0x3f, 0xf5, 0x45, 0x1a, 0x86, 0xf6, 0x00, 0x8c, 0x91, 0x90, 0xb5, 0x43, 0xa3, 0x77, 0xc1,
	0xec, 0x86, 0x57, 0x95, 0xbd, 0xbc, 0x6a, 0xff, 0xae, 0x40, 0xa5, 0x47, 0xfd, 0x51, 0x4c, 0x26,
	0x3b, 0xef, 0xc8, 0x3f, 0x38, 0x63, 0x1a, 0xb0, 0x8f, 0xd2, 0x05, 0x2a, 0x96, 0x6b, 0x81, 0x79,
	0xc9, 0x8c, 0x59, 0xa5, 0x23, 0x55, 0xd4, 0x8b, 0xb5, 0x70, 0x36, 0xf9, 0x99, 0x93, 0x24, 0xf2,
	0xc2, 0xdc, 0xf6, 0xcb, 0xfd, 0xd2, 0x5d, 0xda, 0x0e, 0x77, 0x55, 0xd6, 0xdc, 0x65, 0x82, 0x3a,
	0x99, 0x32, 0x39, 0xec, 0x2a, 0x16, 0x4b, 0xfb, 0x57, 0x05, 0xa0, 0x47, 0xfd, 0x2e, 0xe1, 0x5e,
	0x10, 0x32, 0xf4, 0x08, 0x4a, 0x2c, 0x26, 0x93, 0xdc, 0xe4, 0xff, 0xbb, 0x61, 0x72, 0xd1, 0x1d,
	0x96, 0x29, 0x2b, 0xa7, 0x16, 0xff, 0xd5, 0xa9, 0x87, 0x00, 0xd2, 0x98, 0xd9, 0x64, 0xd5, 0x6d,
	0xab, 0x1e, 0x02, 0x70, 0xc2, 0x78, 0xee, 0x9e, 0x52, 0xe6, 0x44, 0x81, 0x48, 0xe7, 0xd8, 0x2f,
	0xa4, 0xae, 0x83, 0x80, 0x71, 0xd4, 0x82, 0xca, 0x34, 0x3b, 0x69, 0x3e, 0x1d, 0xeb, 0xc6, 0x09,
	0xf3, 0x4e, 0xf0, 0x22, 0xd1, 0xfe, 0x45, 0x01, 0x2d, 0x9f, 0xf0, 0x5d, 0xd0, 0xe6, 0x64, 0xbe,
	0x78, 0x1f, 0x55, 0x9c, 0xef, 0x96, 0x23, 0x28, 0xae, 0x8d, 0x60, 0x5d, 0x6e, 0x75, 0x4b, 0xee,
	0x43, 0x80, 0x19, 0x5d, 0x5e, 0x8b, 0x92, 0x14, 0x5d, 0x9f, 0xd1, 0xc5, 0x8d, 0x78, 0x08, 0x35,
	0x96, 0xc6, 0x42, 0x70, 0xe6, 0x0a, 0xb9, 0xb3, 0x69, 0x19, 0x0b, 0xac, 0x33, 0x65, 0xf6, 0x53,
	0x00, 0x9c, 0x46, 0xc2, 0x4c, 0x84, 0xfd, 0xb7, 0x97, 0xc5, 0xae, 0x83, 0x21, 0x4b, 0x58, 0x4c,
	0x23, 0x46, 0xec, 0xe7, 0x50, 0xbf, 0x8c, 0xa7, 0x42, 0xe4, 0x7d, 0x48, 0x4c, 0x68, 0x2c, 0xaa,
	0x72, 0x9e, 0x16, 0x18, 0xfd, 0x20, 0x0c, 0xf7, 0x62, 0x69, 0x40, 0x2d, 0xab, 0xc9, 0x39, 0xea,
	0x60, 0x88, 0xf1, 0xe4, 0x1c, 0xf6, 0x4b, 0xa8, 0x65, 0xdb, 0x2c, 0x8c, 0xbe, 0x83, 0xd2, 0x07,
	0xea, 0x2f, 0x46, 0x76, 0xff, 0x06, 0xe9, 0xea, 0x8d, 0xc5, 0x32, 0xd1, 0x3e, 0x80, 0x7a, 0x36,
	0xb1, 0x05, 0x63, 0x07, 0x1a, 0x0b, 0x20, 0xe7, 0x7c, 0x0a, 0xda, 0x44, 0x22, 0xf9, 0x51, 0xb7,
	0xae, 0xe9, 0xda, 0xbd, 0xc6, 0x79, 0xe2, 0x63, 0x02, 0xb7, 0x77, 0xfc, 0x02, 0x22, 0x03, 0x2a,
	0x97, 0xc3, 0xfe, 0xf0, 0xfc, 0xed, 0xd0, 0x2c, 0xa0, 0x2a, 0x94, 0xba, 0x67, 0xa3, 0xbe, 0xa9,
	0xa0, 0x1a, 0x54, 0x9d, 0x9f, 0xc6, 0x0e, 0x1e, 0xb6, 0x07, 0x66, 0x11, 0x01, 0x68, 0x23, 0x07,
	0xbf, 0x71, 0xb0, 0xa9, 0x8a, 0x82, 0xa1, 0x33, 0x7e, 0x7b, 0x8e, 0xfb, 0x66, 0x09, 0x99, 0x50,
	0x6b, 0x77, 0x3a, 0xce, 0x68, 0xe4, 0x5e, 0x9c, 0x9f, 0x0d, 0xc7, 0x66, 0xf9, 0xf1, 0x6f, 0x0a,
	0x94, 0xa5, 0xfb, 0xb3, 0x98, 0x60, 0x1e, 0x38, 0xdd, 0x53, 0xa7, 0x6b, 0x16, 0x04, 0xe9, 0xc9,
	0xe5, 0xd9, 0xa0, 0x7b, 0x36, 0x3c, 0x35, 0x15, 0xa4, 0x43, 0x59, 0xec, 0xc6, 0x66, 0x51, 0x70,
	0xe2, 0xcb, 0xe1, 0x50, 0xe0, 0x2a, 0xba, 0x0d, 0x07, 0x97, 0x17, 0xdd, 0xf6, 0xd8, 0x71, 0x47,
	0xe3, 0x36, 0x1e, 0x0b, 0xb0, 0x24, 0x4a, 0x25, 0x28, 0x76, 0x65, 0x91, 0xdf, 0x3f, 0x1b, 0x0c,
	0xc4, 0x46, 0x93, 0x87, 0x76, 0xda, 0x5d, 0xb3, 0x22, 0xe0, 0x0b, 0x67, 0x28, 0xe9, 0xab, 0x59,
	0x2f, 0x4e, 0xd7, 0xd4, 0x11, 0x82, 0xc6, 0x09, 0x3e, 0x1b, 0xf6, 0xdd, 0xf3, 0x57, 0x6e, 0xd7,
	0x69, 0x8f, 0x5f, 0x9b, 0xd0, 0xfa, 0x5c, 0x04, 0x38, 0x11, 0x82, 0x49, 0xa9, 0xd0, 0x4b, 0xd0,
	0x70, 0x1a, 0x89, 0xdf, 0xf7, 0xad, 0x2b, 0xb5, 0xb2, 0x69, 0xf3, 0xde, 0x8e, 0x48, 0xee, 0x80,
	0x02, 0x7a, 0x0d, 0x7a, 0xe6, 0x2c, 0xc1, 0xb1, 0x35, 0xe3, 0x0d, 0xa3, 0x36, 0x1f, 0xec, 0x0e,
	0x2e, 0x99, 0x4e, 0xa0, 0x22, 0xdc, 0x25, 0x78, 0xb6, 0xbe, 0xb8, 0x66, 0xd4, 0x66, 0x73, 0x57,
	0x68, 0xc9, 0xd1, 0x81, 0xaa, 0xb0, 0x60, 0x8f, 0xfa, 0x6c, 0x9b, 0x64, 0xcd, 0xa9, 0xdb, 0x24,
	0xeb, 0xae, 0xb5, 0x0b, 0xa8, 0xb7, 0xf9, 0xfb, 0xb0, 0xd5, 0xd4, 0x86, 0x43, 0xb7, 0x9b, 0xda,
	0x74, 0xab, 0x5d, 0x68, 0xfd, 0x51, 0x84, 0xda, 0x29, 0x5d, 0x13, 0xfc, 0x07, 0xd0, 0xb2, 0xce,
	0xd1, 0xee, 0x57, 0xb6, 0xb9, 0xf5, 0xa0, 0x66, 0x7f, 0xf9, 0x0a, 0xe8, 0x47, 0xa8, 0x4a, 0x16,
	0x21, 0xcf, 0x7e, 0x95, 0xcf, 0x40, 0xc5, 0x69, 0xb4, 0x67, 0xd1, 0x73, 0x28, 0x09, 0x69, 0xf7,
	0xaf, 0x92, 0xef, 0xf5, 0xae, 0x70, 0xf3, 0x26, 0x95, 0xc8, 0x95, 0xad, 0xe9, 0xa7, 0x84, 0xe7,
	0x6a, 0xef, 0x2c, 0xbd, 0xb3, 0x4b, 0x65, 0xbb, 0xe0, 0x6b, 0xf2, 0x7f, 0xf2, 0xb3, 0xbf, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0x56, 0x8d, 0xf7, 0x36, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BuildSlaveClient is the client API for BuildSlave service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BuildSlaveClient interface {
	RunJob(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	UpdateJob(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	KillJob(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
	ListJobs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	SlaveConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
}

type buildSlaveClient struct {
	cc *grpc.ClientConn
}

func NewBuildSlaveClient(cc *grpc.ClientConn) BuildSlaveClient {
	return &buildSlaveClient{cc}
}

func (c *buildSlaveClient) RunJob(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, "/gobuildslave.BuildSlave/RunJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildSlaveClient) UpdateJob(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/gobuildslave.BuildSlave/UpdateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildSlaveClient) KillJob(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, "/gobuildslave.BuildSlave/KillJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildSlaveClient) ListJobs(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/gobuildslave.BuildSlave/ListJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildSlaveClient) SlaveConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, "/gobuildslave.BuildSlave/SlaveConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildSlaveServer is the server API for BuildSlave service.
type BuildSlaveServer interface {
	RunJob(context.Context, *RunRequest) (*RunResponse, error)
	UpdateJob(context.Context, *UpdateRequest) (*UpdateResponse, error)
	KillJob(context.Context, *KillRequest) (*KillResponse, error)
	ListJobs(context.Context, *ListRequest) (*ListResponse, error)
	SlaveConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
}

func RegisterBuildSlaveServer(s *grpc.Server, srv BuildSlaveServer) {
	s.RegisterService(&_BuildSlave_serviceDesc, srv)
}

func _BuildSlave_RunJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildSlaveServer).RunJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.BuildSlave/RunJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildSlaveServer).RunJob(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildSlave_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildSlaveServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.BuildSlave/UpdateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildSlaveServer).UpdateJob(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildSlave_KillJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildSlaveServer).KillJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.BuildSlave/KillJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildSlaveServer).KillJob(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildSlave_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildSlaveServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.BuildSlave/ListJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildSlaveServer).ListJobs(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildSlave_SlaveConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildSlaveServer).SlaveConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.BuildSlave/SlaveConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildSlaveServer).SlaveConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BuildSlave_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gobuildslave.BuildSlave",
	HandlerType: (*BuildSlaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunJob",
			Handler:    _BuildSlave_RunJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _BuildSlave_UpdateJob_Handler,
		},
		{
			MethodName: "KillJob",
			Handler:    _BuildSlave_KillJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _BuildSlave_ListJobs_Handler,
		},
		{
			MethodName: "SlaveConfig",
			Handler:    _BuildSlave_SlaveConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slave.proto",
}

// GoBuildSlaveClient is the client API for GoBuildSlave service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoBuildSlaveClient interface {
	Update(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error)
	BuildJob(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error)
	Run(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error)
	Kill(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobList, error)
	GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Config, error)
}

type goBuildSlaveClient struct {
	cc *grpc.ClientConn
}

func NewGoBuildSlaveClient(cc *grpc.ClientConn) GoBuildSlaveClient {
	return &goBuildSlaveClient{cc}
}

func (c *goBuildSlaveClient) Update(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gobuildslave.GoBuildSlave/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBuildSlaveClient) BuildJob(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gobuildslave.GoBuildSlave/BuildJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBuildSlaveClient) Run(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gobuildslave.GoBuildSlave/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBuildSlaveClient) Kill(ctx context.Context, in *JobSpec, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/gobuildslave.GoBuildSlave/Kill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBuildSlaveClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*JobList, error) {
	out := new(JobList)
	err := c.cc.Invoke(ctx, "/gobuildslave.GoBuildSlave/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goBuildSlaveClient) GetConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Config, error) {
	out := new(Config)
	err := c.cc.Invoke(ctx, "/gobuildslave.GoBuildSlave/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoBuildSlaveServer is the server API for GoBuildSlave service.
type GoBuildSlaveServer interface {
	Update(context.Context, *JobSpec) (*Empty, error)
	BuildJob(context.Context, *JobSpec) (*Empty, error)
	Run(context.Context, *JobSpec) (*Empty, error)
	Kill(context.Context, *JobSpec) (*Empty, error)
	List(context.Context, *Empty) (*JobList, error)
	GetConfig(context.Context, *Empty) (*Config, error)
}

func RegisterGoBuildSlaveServer(s *grpc.Server, srv GoBuildSlaveServer) {
	s.RegisterService(&_GoBuildSlave_serviceDesc, srv)
}

func _GoBuildSlave_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildSlaveServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.GoBuildSlave/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildSlaveServer).Update(ctx, req.(*JobSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBuildSlave_BuildJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildSlaveServer).BuildJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.GoBuildSlave/BuildJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildSlaveServer).BuildJob(ctx, req.(*JobSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBuildSlave_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildSlaveServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.GoBuildSlave/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildSlaveServer).Run(ctx, req.(*JobSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBuildSlave_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildSlaveServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.GoBuildSlave/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildSlaveServer).Kill(ctx, req.(*JobSpec))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBuildSlave_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildSlaveServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.GoBuildSlave/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildSlaveServer).List(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoBuildSlave_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoBuildSlaveServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gobuildslave.GoBuildSlave/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoBuildSlaveServer).GetConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoBuildSlave_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gobuildslave.GoBuildSlave",
	HandlerType: (*GoBuildSlaveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _GoBuildSlave_Update_Handler,
		},
		{
			MethodName: "BuildJob",
			Handler:    _GoBuildSlave_BuildJob_Handler,
		},
		{
			MethodName: "Run",
			Handler:    _GoBuildSlave_Run_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _GoBuildSlave_Kill_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GoBuildSlave_List_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _GoBuildSlave_GetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slave.proto",
}
